name: grpc_flutter_client

description: A new Flutter project.

version: 1.0.0
publish_to: none  

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.2.4
  protobuf: ^3.1.0
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  provider: ^6.1.1 

dev_dependencies:
  flutter_lints: ^2.0.0
